# Generated by Django 4.2.6 on 2023-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
